### ISSUE TITLE
create synced_video entry for lbry-uploader publishes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-first#1]
Or some other way to mark the video so it's not synced back. I assume some creators will go exlclusive lbry first and we can disable sync, but others may want to experiment with some content first.

**Comment by kauffj** [comment]
and record a column that it came from us!

**Comment by tiger5226** [comment]
For this we can call the `/yt/video_status` API of internal-apis, the parameters are:

```golang
v.Field(&params.YoutubeChannelID, v.Required, validator.YoutubeChannelID),
		v.Field(&params.ClaimName, is.PrintableASCII),
		v.Field(&params.VideoID, is.PrintableASCII),
		v.Field(&params.ClaimID, validator.ClaimID),
		v.Field(&params.Status, v.Required, is.PrintableASCII),
		v.Field(&params.FailureReason, is.PrintableASCII),
		v.Field(&params.PublishedAt),
		v.Field(&params.Size),
		v.Field(&params.MetadataVersion),
		v.Field(&params.Transferred),
```

This would need to be solved first.
https://github.com/lbryio/internal-apis/issues/1362

**Comment by tiger5226** [comment]
I wrote the logic for this, but I have a big issue. The synced video table requires a claim_id for the synced video. I have the claim name from the app call, but not the claim id. It doesn't appear to be in the response from the publish call.

 @seanyesmunt - Do you know where I can easily get it so I can pass it into the youtube upload call to lbry-first after the lbry publish is successful?

**Comment by tiger5226** [comment]
This is written,  but needs testing still with a ytsync account which is a bit complicated, so I need to data or update data in my db to test this one better.
